In [1]:
import pandas as pd
import numpy as np

In [2]:
from features import utils

In [3]:
train2016 = pd.read_csv('data/train_2016_v2.csv', parse_dates=['transactiondate'])
prop2016 = pd.read_csv('data/properties_2016.csv')
train2017 = pd.read_csv('data/train_2017.csv', parse_dates=['transactiondate'])
prop2017 = pd.read_csv('data/properties_2017.csv')

/usr/local/google/home/hzn/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (22,32,34,49,55) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/usr/local/google/home/hzn/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (49) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [11]:
(prop2017['latitude'].min(), prop2017['latitude'].max())

(33324388.0, 34819650.0)

In [12]:
(prop2017['longitude'].min(), prop2017['longitude'].max())

(-119475780.0, -117554316.0)

In [7]:
tax_columns = ['taxvaluedollarcnt', 'structuretaxvaluedollarcnt',
                'landtaxvaluedollarcnt', 'taxamount' ,'assessmentyear',
                'taxdelinquencyflag' ,'taxdelinquencyyear']
prop2017.drop(tax_columns, axis=1, inplace=True)
tax2016 = prop2016[['parcelid', *tax_columns]]
# prop2017[tax_columns] = prop2016[tax_columns]
prop = prop2017.merge(tax2016, 'left', 'parcelid')

In [8]:
prop[tax_columns].describe()

,taxvaluedollarcnt,structuretaxvaluedollarcnt,landtaxvaluedollarcnt,taxamount,assessmentyear,taxdelinquencyyear
count,2.942667e+06,2.930235e+06,2.917484e+06,2.953967e+06,2.973778e+06,56464.000000
mean,4.204790e+05,1.708836e+05,2.524780e+05,5.377607e+03,2.014999e+03,13.892409
std,7.263467e+05,4.020683e+05,4.450132e+05,9.183107e+03,3.683161e-02,2.581006
min,1.000000e+00,1.000000e+00,1.000000e+00,1.340000e+00,2.000000e+03,0.000000
25%,1.796750e+05,7.480000e+04,7.483600e+04,2.461070e+03,2.015000e+03,14.000000
50%,3.060860e+05,1.225900e+05,1.670420e+05,3.991780e+03,2.015000e+03,14.000000
75%,4.880000e+05,1.968890e+05,3.069180e+05,6.201005e+03,2.015000e+03,15.000000
max,2.827860e+08,2.514860e+08,9.024622e+07,3.458861e+06,2.016000e+03,99.000000

In [9]:
tax2016.describe()

,parcelid,taxvaluedollarcnt,structuretaxvaluedollarcnt,landtaxvaluedollarcnt,taxamount,assessmentyear,taxdelinquencyyear
count,2.985217e+06,2.942667e+06,2.930235e+06,2.917484e+06,2.953967e+06,2.973778e+06,56464.000000
mean,1.332586e+07,4.204790e+05,1.708836e+05,2.524780e+05,5.377607e+03,2.014999e+03,13.892409
std,7.909966e+06,7.263467e+05,4.020683e+05,4.450132e+05,9.183107e+03,3.683161e-02,2.581006
min,1.071172e+07,1.000000e+00,1.000000e+00,1.000000e+00,1.340000e+00,2.000000e+03,0.000000
25%,1.164371e+07,1.796750e+05,7.480000e+04,7.483600e+04,2.461070e+03,2.015000e+03,14.000000
50%,1.254509e+07,3.060860e+05,1.225900e+05,1.670420e+05,3.991780e+03,2.015000e+03,14.000000
75%,1.409712e+07,4.880000e+05,1.968890e+05,3.069180e+05,6.201005e+03,2.015000e+03,15.000000
max,1.696019e+08,2.827860e+08,2.514860e+08,9.024622e+07,3.458861e+06,2.016000e+03,99.000000

In [6]:
train2017.columns

Index(['parcelid', 'logerror', 'transactiondate'], dtype='object')

In [7]:
train2017.describe()

           parcelid      logerror
count  7.761300e+04  77613.000000
mean   1.300781e+07      0.016755
std    3.518717e+06      0.170887
min    1.071186e+07     -4.655420
25%    1.153821e+07     -0.024325
50%    1.253004e+07      0.006670
75%    1.421101e+07      0.039295
max    1.676893e+08      5.262999

In [11]:
train2016.describe()

           parcelid      logerror
count  9.027500e+04  90275.000000
mean   1.298466e+07      0.011457
std    2.504510e+06      0.161079
min    1.071174e+07     -4.605000
25%    1.155950e+07     -0.025300
50%    1.254734e+07      0.006000
75%    1.422755e+07      0.039200
max    1.629608e+08      4.737000

In [14]:
# House sold in both 2016 and 2017
len(set(train2017['parcelid'].unique()).intersection(set(train2016['parcelid'].unique())))

2354

In [20]:
for col in prop2017.columns:
    print('-----------------------------------------------')
    print('2017 %s:' %col)
    print(prop2017[col].describe())
    print('\n2016 %s:' %col)
    print(prop2016[col].describe())
    print('-----------------------------------------------\n')

-----------------------------------------------
2017 parcelid:
count    2.985217e+06
mean     1.332586e+07
std      7.909966e+06
min      1.071172e+07
25%      1.164371e+07
50%      1.254509e+07
75%      1.409712e+07
max      1.696019e+08
Name: parcelid, dtype: float64

2016 parcelid:
count    2.985217e+06
mean     1.332586e+07
std      7.909966e+06
min      1.071172e+07
25%      1.164371e+07
50%      1.254509e+07
75%      1.409712e+07
max      1.696019e+08
Name: parcelid, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 airconditioningtypeid:
count    815362.000000
mean          1.945723
std           3.160507
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max          13.000000
Name: airconditioningtypeid, dtype: float64

2016 airconditioningtypeid:
count    811519.000000
mean          1.931166
std           3.153373
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max          13.000000
Name: airconditioningtypeid, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 architecturalstyletypeid:
count    6061.000000
mean        7.202607
std         2.436290
min         2.000000
25%         7.000000
50%         7.000000
75%         7.000000
max        27.000000
Name: architecturalstyletypeid, dtype: float64

2016 architecturalstyletypeid:
count    6061.000000
mean        7.202607
std         2.436318
min         2.000000
25%         7.000000
50%         7.000000
75%         7.000000
max        27.000000
Name: architecturalstyletypeid, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 basementsqft:
count    1627.000000
mean      647.220652
std       538.787104
min        20.000000
25%       272.000000
50%       535.000000
75%       847.500000
max      8516.000000
Name: basementsqft, dtype: float64

2016 basementsqft:
count    1628.000000
mean      646.883301
std       538.793274
min        20.000000
25%       272.000000
50%       534.000000
75%       847.250000
max      8516.000000
Name: basementsqft, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 bathroomcnt:
count    2.982260e+06
mean     2.216196e+00
std      1.078250e+00
min      0.000000e+00
25%      2.000000e+00
50%      2.000000e+00
75%      3.000000e+00
max      3.200000e+01
Name: bathroomcnt, dtype: float64

2016 bathroomcnt:
count    2.973755e+06
mean     2.209143e+00
std      1.079355e+00
min      0.000000e+00
25%      2.000000e+00
50%      2.000000e+00
75%      3.000000e+00
max      2.000000e+01
Name: bathroomcnt, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 bedroomcnt:
count    2.982272e+06
mean     3.093362e+00
std      1.271569e+00
min      0.000000e+00
25%      2.000000e+00
50%      3.000000e+00
75%      4.000000e+00
max      2.500000e+01
Name: bedroomcnt, dtype: float64

2016 bedroomcnt:
count    2.973767e+06
mean     3.088949e+00
std      1.273220e+00
min      0.000000e+00
25%      2.000000e+00
50%      3.000000e+00
75%      4.000000e+00
max      2.000000e+01
Name: bedroomcnt, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 buildingclasstypeid:
count    12731.000000
mean         3.734742
std          0.500371
min          1.000000
25%          3.000000
50%          4.000000
75%          4.000000
max          5.000000
Name: buildingclasstypeid, dtype: float64

2016 buildingclasstypeid:
count    12629.000000
mean         3.725948
std          0.501724
min          1.000000
25%          3.000000
50%          4.000000
75%          4.000000
max          5.000000
Name: buildingclasstypeid, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 buildingqualitytypeid:
count    1.941395e+06
mean     6.280822e+00
std      1.729923e+00
min      1.000000e+00
25%      5.000000e+00
50%      6.000000e+00
75%      8.000000e+00
max      1.200000e+01
Name: buildingqualitytypeid, dtype: float64

2016 buildingqualitytypeid:
count    1.938488e+06
mean     5.784787e+00
std      1.804708e+00
min      1.000000e+00
25%      4.000000e+00
50%      7.000000e+00
75%      7.000000e+00
max      1.200000e+01
Name: buildingqualitytypeid, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 calculatedbathnbr:
count    2.868061e+06
mean     2.303826e+00
std      1.003243e+00
min      1.000000e+00
25%      2.000000e+00
50%      2.000000e+00
75%      3.000000e+00
max      3.200000e+01
Name: calculatedbathnbr, dtype: float64

2016 calculatedbathnbr:
count    2.856305e+06
mean     2.299263e+00
std      1.001426e+00
min      1.000000e+00
25%      2.000000e+00
50%      2.000000e+00
75%      3.000000e+00
max      2.000000e+01
Name: calculatedbathnbr, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 decktypeid:
count    17379.0
mean        66.0
std          0.0
min         66.0
25%         66.0
50%         66.0
75%         66.0
max         66.0
Name: decktypeid, dtype: float64

2016 decktypeid:
count    17096.0
mean        66.0
std          0.0
min         66.0
25%         66.0
50%         66.0
75%         66.0
max         66.0
Name: decktypeid, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 finishedfloor1squarefeet:
count    203758.000000
mean       1379.780460
std         634.422849
min           1.000000
25%        1010.000000
50%        1281.000000
75%        1615.000000
max       31303.000000
Name: finishedfloor1squarefeet, dtype: float64

2016 finishedfloor1squarefeet:
count    202717.000000
mean       1380.660400
std         632.858948
min           3.000000
25%        1012.000000
50%        1283.000000
75%        1615.000000
max       31303.000000
Name: finishedfloor1squarefeet, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 calculatedfinishedsquarefeet:
count    2.940120e+06
mean     1.831455e+03
std      1.954198e+03
min      1.000000e+00
25%      1.215000e+03
50%      1.574000e+03
75%      2.140000e+03
max      9.525760e+05
Name: calculatedfinishedsquarefeet, dtype: float64

2016 calculatedfinishedsquarefeet:
count    2.929652e+06
mean     1.826764e+03
std      1.814387e+03
min      1.000000e+00
25%      1.213000e+03
50%      1.572000e+03
75%      2.136000e+03
max      9.525760e+05
Name: calculatedfinishedsquarefeet, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 finishedsquarefeet12:
count    2.720786e+06
mean     1.764045e+03
std      1.031383e+03
min      1.000000e+00
25%      1.198000e+03
50%      1.542000e+03
75%      2.075000e+03
max      4.270790e+05
Name: finishedsquarefeet12, dtype: float64

2016 finishedsquarefeet12:
count    2.709184e+06
mean     1.759635e+03
std      9.696898e+02
min      1.000000e+00
25%      1.196000e+03
50%      1.539000e+03
75%      2.070000e+03
max      2.903450e+05
Name: finishedsquarefeet12, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 finishedsquarefeet13:
count    7671.000000
mean     1178.916699
std       357.093554
min       120.000000
25%       960.000000
50%      1296.000000
75%      1440.000000
max      2688.000000
Name: finishedsquarefeet13, dtype: float64

2016 finishedsquarefeet13:
count    7672.000000
mean     1178.900635
std       357.070312
min       120.000000
25%       960.000000
50%      1296.000000
75%      1440.000000
max      2688.000000
Name: finishedsquarefeet13, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 finishedsquarefeet15:
count    190185.000000
mean       2754.869233
std        5999.380115
min         112.000000
25%        1696.000000
50%        2173.000000
75%        2975.000000
max      820242.000000
Name: finishedsquarefeet15, dtype: float64

2016 finishedsquarefeet15:
count    190798.000000
mean       2739.171631
std        5446.928711
min         112.000000
25%        1694.000000
50%        2172.000000
75%        2976.000000
max      820242.000000
Name: finishedsquarefeet15, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 finishedsquarefeet50:
count    203758.000000
mean       1392.029093
std         682.323851
min           3.000000
25%        1012.000000
50%        1284.000000
75%        1619.000000
max       41906.000000
Name: finishedsquarefeet50, dtype: float64

2016 finishedsquarefeet50:
count    202717.000000
mean       1388.974243
std         664.469543
min           3.000000
25%        1013.000000
50%        1284.000000
75%        1618.000000
max       31303.000000
Name: finishedsquarefeet50, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 finishedsquarefeet6:
count     21482.000000
mean       2427.555209
std        7786.185183
min         117.000000
25%        1072.000000
50%        2008.000000
75%        3411.000000
max      952576.000000
Name: finishedsquarefeet6, dtype: float64

2016 finishedsquarefeet6:
count     22001.000000
mean       2414.341797
std        7695.268555
min         117.000000
25%        1079.000000
50%        1992.000000
75%        3366.000000
max      952576.000000
Name: finishedsquarefeet6, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 fips:
count    2.982285e+06
mean     6.048053e+03
std      2.024082e+01
min      6.037000e+03
25%      6.037000e+03
50%      6.037000e+03
75%      6.059000e+03
max      6.111000e+03
Name: fips, dtype: float64

2016 fips:
count    2.973780e+06
mean     6.130900e+03
std      8.541431e+01
min      6.037000e+03
25%      6.037000e+03
50%      6.037000e+03
75%      6.059000e+03
max      6.111000e+03
Name: fips, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 fireplacecnt:
count    313124.000000
mean          1.168959
std           0.461855
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max           9.000000
Name: fireplacecnt, dtype: float64

2016 fireplacecnt:
count    312637.000000
mean          1.168710
std           0.461005
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max           9.000000
Name: fireplacecnt, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 fullbathcnt:
count    2.868061e+06
mean     2.248089e+00
std      9.929959e-01
min      1.000000e+00
25%      2.000000e+00
50%      2.000000e+00
75%      3.000000e+00
max      3.200000e+01
Name: fullbathcnt, dtype: float64

2016 fullbathcnt:
count    2.856305e+06
mean     2.244165e+00
std      9.792719e-01
min      1.000000e+00
25%      2.000000e+00
50%      2.000000e+00
75%      3.000000e+00
max      2.000000e+01
Name: fullbathcnt, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 garagecarcnt:
count    891008.000000
mean          1.826581
std           0.608934
min           0.000000
25%           2.000000
50%           2.000000
75%           2.000000
max          25.000000
Name: garagecarcnt, dtype: float64

2016 garagecarcnt:
count    883267.000000
mean          1.823517
std           0.610063
min           0.000000
25%           2.000000
50%           2.000000
75%           2.000000
max          25.000000
Name: garagecarcnt, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 garagetotalsqft:
count    891008.00000
mean        383.15622
std         246.21942
min           0.00000
25%         312.00000
50%         441.00000
75%         494.00000
max        7749.00000
Name: garagetotalsqft, dtype: float64

2016 garagetotalsqft:
count    883267.000000
mean        383.638367
std         245.452042
min           0.000000
25%         324.000000
50%         441.000000
75%         494.000000
max        7749.000000
Name: garagetotalsqft, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 hashottuborspa:
count     50062
unique        1
top        True
freq      50062
Name: hashottuborspa, dtype: object

2016 hashottuborspa:
count     69014
unique        1
top        True
freq      69014
Name: hashottuborspa, dtype: object
-----------------------------------------------

-----------------------------------------------
2017 heatingorsystemtypeid:
count    1.869164e+06
mean     4.083750e+00
std      3.286780e+00
min      1.000000e+00
25%      2.000000e+00
50%      2.000000e+00
75%      7.000000e+00
max      2.400000e+01
Name: heatingorsystemtypeid, dtype: float64

2016 heatingorsystemtypeid:
count    1.806401e+06
mean     4.012053e+00
std      3.285914e+00
min      1.000000e+00
25%      2.000000e+00
50%      2.000000e+00
75%      7.000000e+00
max      2.400000e+01
Name: heatingorsystemtypeid, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 latitude:
count    2.982285e+06
mean     3.400131e+07
std      2.435157e+05
min      3.332439e+07
25%      3.382740e+07
50%      3.400807e+07
75%      3.416186e+07
max      3.481965e+07
Name: latitude, dtype: float64

2016 latitude:
count    2.973780e+06
mean     3.363516e+07
std      4.396144e+05
min      3.332439e+07
25%      3.382768e+07
50%      3.400825e+07
75%      3.416186e+07
max      3.481965e+07
Name: latitude, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 longitude:
count    2.982285e+06
mean    -1.182017e+08
std      3.455918e+05
min     -1.194758e+08
25%     -1.183929e+08
50%     -1.181721e+08
75%     -1.179489e+08
max     -1.175543e+08
Name: longitude, dtype: float64

2016 longitude:
count    2.973780e+06
mean    -1.207603e+08
std      2.579615e+06
min     -1.194758e+08
25%     -1.183930e+08
50%     -1.181725e+08
75%     -1.179495e+08
max     -1.175543e+08
Name: longitude, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 lotsizesquarefeet:
count    2.712511e+06
mean     2.260376e+04
std      2.499836e+05
min      1.000000e+02
25%      5.683000e+03
50%      7.000000e+03
75%      9.893000e+03
max      3.710005e+08
Name: lotsizesquarefeet, dtype: float64

2016 lotsizesquarefeet:
count    2.709118e+06
mean     2.282076e+04
std      3.372850e+05
min      1.000000e+02
25%      5.688000e+03
50%      7.000000e+03
75%      9.898000e+03
max      3.282638e+08
Name: lotsizesquarefeet, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 poolcnt:
count    539632.0
mean          1.0
std           0.0
min           1.0
25%           1.0
50%           1.0
75%           1.0
max           1.0
Name: poolcnt, dtype: float64

2016 poolcnt:
count    517534.0
mean          1.0
std           0.0
min           1.0
25%           1.0
50%           1.0
75%           1.0
max           1.0
Name: poolcnt, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 poolsizesum:
count    27958.000000
mean       519.715430
std        191.325869
min         19.000000
25%        430.000000
50%        495.000000
75%        594.000000
max      17410.000000
Name: poolsizesum, dtype: float64

2016 poolsizesum:
count    27960.000000
mean       519.710999
std        191.326157
min         19.000000
25%        430.000000
50%        495.000000
75%        594.000000
max      17410.000000
Name: poolsizesum, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 pooltypeid10:
count    17006.0
mean         1.0
std          0.0
min          1.0
25%          1.0
50%          1.0
75%          1.0
max          1.0
Name: pooltypeid10, dtype: float64

2016 pooltypeid10:
count    36939.0
mean         1.0
std          0.0
min          1.0
25%          1.0
50%          1.0
75%          1.0
max          1.0
Name: pooltypeid10, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 pooltypeid2:
count    33056.0
mean         1.0
std          0.0
min          1.0
25%          1.0
50%          1.0
75%          1.0
max          1.0
Name: pooltypeid2, dtype: float64

2016 pooltypeid2:
count    32075.0
mean         1.0
std          0.0
min          1.0
25%          1.0
50%          1.0
75%          1.0
max          1.0
Name: pooltypeid2, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 pooltypeid7:
count    505895.0
mean          1.0
std           0.0
min           1.0
25%           1.0
50%           1.0
75%           1.0
max           1.0
Name: pooltypeid7, dtype: float64

2016 pooltypeid7:
count    485459.0
mean          1.0
std           0.0
min           1.0
25%           1.0
50%           1.0
75%           1.0
max           1.0
Name: pooltypeid7, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 propertycountylandusecode:
count     2982218
unique        234
top          0100
freq      1153332
Name: propertycountylandusecode, dtype: object

2016 propertycountylandusecode:
count     2972940
unique        240
top          0100
freq      1153896
Name: propertycountylandusecode, dtype: object
-----------------------------------------------

-----------------------------------------------
2017 propertylandusetypeid:
count    2.982285e+06
mean     2.600508e+02
std      1.593121e+01
min      3.100000e+01
25%      2.610000e+02
50%      2.610000e+02
75%      2.610000e+02
max      2.790000e+02
Name: propertylandusetypeid, dtype: float64

2016 propertylandusetypeid:
count    2.973780e+06
mean     2.563153e+02
std      1.619352e+01
min      3.100000e+01
25%      2.610000e+02
50%      2.610000e+02
75%      2.610000e+02
max      2.750000e+02
Name: propertylandusetypeid, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 propertyzoningdesc:
count     1982471
unique       5651
top          LAR1
freq       275246
Name: propertyzoningdesc, dtype: object

2016 propertyzoningdesc:
count     1978629
unique       5638
top          LAR1
freq       275029
Name: propertyzoningdesc, dtype: object
-----------------------------------------------

-----------------------------------------------
2017 rawcensustractandblock:
count    2.982285e+06
mean     6.048367e+07
std      2.008914e+05
min      6.037101e+07
25%      6.037400e+07
50%      6.037571e+07
75%      6.059042e+07
max      6.111009e+07
Name: rawcensustractandblock, dtype: float64

2016 rawcensustractandblock:
count    2.973780e+06
mean     6.086839e+07
std      4.309542e+05
min      6.037101e+07
25%      6.037320e+07
50%      6.037571e+07
75%      6.059042e+07
max      6.111009e+07
Name: rawcensustractandblock, dtype: float64
-----------------------------------------------

-----------------------------------------------
2017 regionidcity:
count    2.923089e+06
mean     3.498766e+04
std      5.070968e+04
min      3.491000e+03
25%      1.244700e+04
50%      2.521800e+04
75%      4.545700e+04
max      3.965560e+05
Name: regionidcity, dtype: float64

2016 regionidcity:
count    2.922372e+06

In [25]:
for col in prop2017.columns:
    print('-----------------------------------------------')
    print('2017 %s count:' %col)
    print(prop2017[col].count())
    print('\n2016 %s count:' %col)
    print(prop2016[col].count())
    print('-----------------------------------------------\n')

-----------------------------------------------
2017 parcelid count:
2985217

2016 parcelid count:
2985217
-----------------------------------------------

-----------------------------------------------
2017 airconditioningtypeid count:
815362

2016 airconditioningtypeid count:
811519
-----------------------------------------------

-----------------------------------------------
2017 architecturalstyletypeid count:
6061

2016 architecturalstyletypeid count:
6061
-----------------------------------------------

-----------------------------------------------
2017 basementsqft count:
1627

2016 basementsqft count:
1628
-----------------------------------------------

-----------------------------------------------
2017 bathroomcnt count:
2982260

2016 bathroomcnt count:
2973755
-----------------------------------------------

-----------------------------------------------
2017 bedroomcnt count:
2982272

2016 bedroomcnt count:
2973767
-----------------------------------------------

-----------------------------------------------
2017 buildingclasstypeid count:
12731

2016 buildingclasstypeid count:
12629
-----------------------------------------------

-----------------------------------------------
2017 buildingqualitytypeid count:
1941395

2016 buildingqualitytypeid count:
1938488
-----------------------------------------------

-----------------------------------------------
2017 calculatedbathnbr count:
2868061

2016 calculatedbathnbr count:
2856305
-----------------------------------------------

-----------------------------------------------
2017 decktypeid count:
17379

2016 decktypeid count:
17096
-----------------------------------------------

-----------------------------------------------
2017 finishedfloor1squarefeet count:
203758

2016 finishedfloor1squarefeet count:
202717
-----------------------------------------------

-----------------------------------------------
2017 calculatedfinishedsquarefeet count:
2940120

2016 calculatedfinishedsquarefeet count:
2929652
-----------------------------------------------

-----------------------------------------------
2017 finishedsquarefeet12 count:
2720786

2016 finishedsquarefeet12 count:
2709184
-----------------------------------------------

-----------------------------------------------
2017 finishedsquarefeet13 count:
7671

2016 finishedsquarefeet13 count:
7672
-----------------------------------------------

-----------------------------------------------
2017 finishedsquarefeet15 count:
190185

2016 finishedsquarefeet15 count:
190798
-----------------------------------------------

-----------------------------------------------
2017 finishedsquarefeet50 count:
203758

2016 finishedsquarefeet50 count:
202717
-----------------------------------------------

-----------------------------------------------
2017 finishedsquarefeet6 count:
21482

2016 finishedsquarefeet6 count:
22001
-----------------------------------------------

-----------------------------------------------
2017 fips count:
2982285

2016 fips count:
2973780
-----------------------------------------------

-----------------------------------------------
2017 fireplacecnt count:
313124

2016 fireplacecnt count:
312637
-----------------------------------------------

-----------------------------------------------
2017 fullbathcnt count:
2868061

2016 fullbathcnt count:
2856305
-----------------------------------------------

-----------------------------------------------
2017 garagecarcnt count:
891008

2016 garagecarcnt count:
883267
-----------------------------------------------

-----------------------------------------------
2017 garagetotalsqft count:
891008

2016 garagetotalsqft count:
883267
-----------------------------------------------

-----------------------------------------------
2017 hashottuborspa count:
50062

2016 hashottuborspa count:
69014
-----------------------------------------------

-----------------------------------------------
2017 heatingorsystemtypeid count:
1869164

2016 heatingorsystemtypeid count:
1806401
-----------------------------------------------

-----------------------------------------------
2017 latitude count:
2982285

2016 latitude count:
2973780
-----------------------------------------------

-----------------------------------------------
2017 longitude count:
2982285

2016 longitude count:
2973780
-----------------------------------------------

-----------------------------------------------
2017 lotsizesquarefeet count:
2712511

2016 lotsizesquarefeet count:
2709118
-----------------------------------------------

-----------------------------------------------
2017 poolcnt count:
539632

2016 poolcnt count:
517534
-----------------------------------------------

-----------------------------------------------
2017 poolsizesum count:
27958

2016 poolsizesum count:
27960
-----------------------------------------------

-----------------------------------------------
2017 pooltypeid10 count:
17006

2016 pooltypeid10 count:
36939
-----------------------------------------------

-----------------------------------------------
2017 pooltypeid2 count:
33056

2016 pooltypeid2 count:
32075
-----------------------------------------------

-----------------------------------------------
2017 pooltypeid7 count:
505895

2016 pooltypeid7 count:
485459
-----------------------------------------------

-----------------------------------------------
2017 propertycountylandusecode count:
2982218

2016 propertycountylandusecode count:
2972940
-----------------------------------------------

-----------------------------------------------
2017 propertylandusetypeid count:
2982285

2016 propertylandusetypeid count:
2973780
-----------------------------------------------

-----------------------------------------------
2017 propertyzoningdesc count:
1982471

2016 propertyzoningdesc count:
1978629
-----------------------------------------------

-----------------------------------------------
2017 rawcensustractandblock count:
2982285

2016 rawcensustractandblock count:
2973780
-----------------------------------------------

-----------------------------------------------
2017 regionidcity count:
2923089

2016 regionidcity count:
2922372
-----------------------------------------------

-----------------------------------------------
2017 regionidcounty count:
2982285

2016 regionidcounty count:
2973780
-----------------------------------------------

-----------------------------------------------
2017 regionidneighborhood count:
1156741

2016 regionidneighborhood count:
1156402
-----------------------------------------------

-----------------------------------------------
2017 regionidzip count:
2972503

2016 regionidzip count:
2971237
-----------------------------------------------

-----------------------------------------------
2017 roomcnt count:
2982248

2016 roomcnt count:
2973742
-----------------------------------------------

-----------------------------------------------
2017 storytypeid count:
1623

2016 storytypeid count:
1624
-----------------------------------------------

-----------------------------------------------
2017 threequarterbathnbr count:
316357

2016 threequarterbathnbr count:
311631
-----------------------------------------------

-----------------------------------------------
2017 typeconstructiontypeid count:
6746

2016 typeconstructiontypeid count:
6747
-----------------------------------------------

-----------------------------------------------
2017 unitcnt count:
1981042

2016 unitcnt count:
1977490
-----------------------------------------------

-----------------------------------------------
2017 yardbuildingsqft17 count:
81588

2016 yardbuildingsqft17 count:
80355
-----------------------------------------------

-----------------------------------------------
2017 yardbuildingsqft26 count:
2646

2016 yardbuildingsqft26 count:
2647
-----------------------------------------------

-----------------------------------------------
2017 yearbuilt count:
2937384

2016 yearbuilt count:
2925289
-----------------------------------------------

-----------------------------------------------
2017 numberofstories count:
685676

2016 numberofstories count:
682069
-----------------------------------------------

-----------------------------------------------
2017 fireplaceflag count:
5163

2016 fireplaceflag count:
5163
-----------------------------------------------

-----------------------------------------------
2017 structuretaxvaluedollarcnt count:
2938753

2016 structuretaxvaluedollarcnt count:
2930235
-----------------------------------------------

-----------------------------------------------
2017 taxvaluedollarcnt count:
2950951

2016 taxvaluedollarcnt count:
2942667
-----------------------------------------------

-----------------------------------------------
2017 assessmentyear count:
2982284

2016 assessmentyear count:
2973778
-----------------------------------------------

-----------------------------------------------
2017 landtaxvaluedollarcnt count:
2925291

2016 landtaxvaluedollarcnt count:
2917484
-----------------------------------------------

-----------------------------------------------
2017 taxamount count:
2962465

2016 taxamount count:
2953967
-----------------------------------------------

-----------------------------------------------
2017 taxdelinquencyflag count:
56515

2016 taxdelinquencyflag count:
56462
-----------------------------------------------

-----------------------------------------------
2017 taxdelinquencyyear count:
56517

2016 taxdelinquencyyear count:
56464
-----------------------------------------------

-----------------------------------------------
2017 censustractandblock count:
2910232

2016 censustractandblock count:
2910091
-----------------------------------------------

In [28]:
# All columns where 2017 has more data
i = 0
for col in prop2017.columns:
    if prop2017[col].count() > prop2016[col].count():
        i+=1
        print('-----------------------------------------------')
        print('2017 %s count: %d' %(col, prop2017[col].count()))
        print('\n2016 %s count: %d' %(col, prop2016[col].count()))
        print('-----------------------------------------------\n')

print('Total columns with more data: %d' %i)

-----------------------------------------------
2017 airconditioningtypeid count: 815362

2016 airconditioningtypeid count: 811519
-----------------------------------------------

-----------------------------------------------
2017 bathroomcnt count: 2982260

2016 bathroomcnt count: 2973755
-----------------------------------------------

-----------------------------------------------
2017 bedroomcnt count: 2982272

2016 bedroomcnt count: 2973767
-----------------------------------------------

-----------------------------------------------
2017 buildingclasstypeid count: 12731

2016 buildingclasstypeid count: 12629
-----------------------------------------------

-----------------------------------------------
2017 buildingqualitytypeid count: 1941395

2016 buildingqualitytypeid count: 1938488
-----------------------------------------------

-----------------------------------------------
2017 calculatedbathnbr count: 2868061

2016 calculatedbathnbr count: 2856305
-----------------------------------------------

-----------------------------------------------
2017 decktypeid count: 17379

2016 decktypeid count: 17096
-----------------------------------------------

-----------------------------------------------
2017 finishedfloor1squarefeet count: 203758

2016 finishedfloor1squarefeet count: 202717
-----------------------------------------------

-----------------------------------------------
2017 calculatedfinishedsquarefeet count: 2940120

2016 calculatedfinishedsquarefeet count: 2929652
-----------------------------------------------

-----------------------------------------------
2017 finishedsquarefeet12 count: 2720786

2016 finishedsquarefeet12 count: 2709184
-----------------------------------------------

-----------------------------------------------
2017 finishedsquarefeet50 count: 203758

2016 finishedsquarefeet50 count: 202717
-----------------------------------------------

-----------------------------------------------
2017 fips count: 2982285

2016 fips count: 2973780
-----------------------------------------------

-----------------------------------------------
2017 fireplacecnt count: 313124

2016 fireplacecnt count: 312637
-----------------------------------------------

-----------------------------------------------
2017 fullbathcnt count: 2868061

2016 fullbathcnt count: 2856305
-----------------------------------------------

-----------------------------------------------
2017 garagecarcnt count: 891008

2016 garagecarcnt count: 883267
-----------------------------------------------

-----------------------------------------------
2017 garagetotalsqft count: 891008

2016 garagetotalsqft count: 883267
-----------------------------------------------

-----------------------------------------------
2017 heatingorsystemtypeid count: 1869164

2016 heatingorsystemtypeid count: 1806401
-----------------------------------------------

-----------------------------------------------
2017 latitude count: 2982285

2016 latitude count: 2973780
-----------------------------------------------

-----------------------------------------------
2017 longitude count: 2982285

2016 longitude count: 2973780
-----------------------------------------------

-----------------------------------------------
2017 lotsizesquarefeet count: 2712511

2016 lotsizesquarefeet count: 2709118
-----------------------------------------------

-----------------------------------------------
2017 poolcnt count: 539632

2016 poolcnt count: 517534
-----------------------------------------------

-----------------------------------------------
2017 pooltypeid2 count: 33056

2016 pooltypeid2 count: 32075
-----------------------------------------------

-----------------------------------------------
2017 pooltypeid7 count: 505895

2016 pooltypeid7 count: 485459
-----------------------------------------------

-----------------------------------------------
2017 propertycountylandusecode count: 2982218

2016 propertycountylandusecode count: 2972940
-----------------------------------------------

-----------------------------------------------
2017 propertylandusetypeid count: 2982285

2016 propertylandusetypeid count: 2973780
-----------------------------------------------

-----------------------------------------------
2017 propertyzoningdesc count: 1982471

2016 propertyzoningdesc count: 1978629
-----------------------------------------------

-----------------------------------------------
2017 rawcensustractandblock count: 2982285

2016 rawcensustractandblock count: 2973780
-----------------------------------------------

-----------------------------------------------
2017 regionidcity count: 2923089

2016 regionidcity count: 2922372
-----------------------------------------------

-----------------------------------------------
2017 regionidcounty count: 2982285

2016 regionidcounty count: 2973780
-----------------------------------------------

-----------------------------------------------
2017 regionidneighborhood count: 1156741

2016 regionidneighborhood count: 1156402
-----------------------------------------------

-----------------------------------------------
2017 regionidzip count: 2972503

2016 regionidzip count: 2971237
-----------------------------------------------

-----------------------------------------------
2017 roomcnt count: 2982248

2016 roomcnt count: 2973742
-----------------------------------------------

-----------------------------------------------
2017 threequarterbathnbr count: 316357

2016 threequarterbathnbr count: 311631
-----------------------------------------------

-----------------------------------------------
2017 unitcnt count: 1981042

2016 unitcnt count: 1977490
-----------------------------------------------

-----------------------------------------------
2017 yardbuildingsqft17 count: 81588

2016 yardbuildingsqft17 count: 80355
-----------------------------------------------

-----------------------------------------------
2017 yearbuilt count: 2937384

2016 yearbuilt count: 2925289
-----------------------------------------------

-----------------------------------------------
2017 numberofstories count: 685676

2016 numberofstories count: 682069
-----------------------------------------------

-----------------------------------------------
2017 structuretaxvaluedollarcnt count: 2938753

2016 structuretaxvaluedollarcnt count: 2930235
-----------------------------------------------

-----------------------------------------------
2017 taxvaluedollarcnt count: 2950951

2016 taxvaluedollarcnt count: 2942667
-----------------------------------------------

-----------------------------------------------
2017 assessmentyear count: 2982284

2016 assessmentyear count: 2973778
-----------------------------------------------

-----------------------------------------------
2017 landtaxvaluedollarcnt count: 2925291

2016 landtaxvaluedollarcnt count: 2917484
-----------------------------------------------

-----------------------------------------------
2017 taxamount count: 2962465

2016 taxamount count: 2953967
-----------------------------------------------

-----------------------------------------------
2017 taxdelinquencyflag count: 56515

2016 taxdelinquencyflag count: 56462
-----------------------------------------------

-----------------------------------------------
2017 taxdelinquencyyear count: 56517

2016 taxdelinquencyyear count: 56464
-----------------------------------------------

-----------------------------------------------
2017 censustractandblock count: 2910232

2016 censustractandblock count: 2910091
-----------------------------------------------

Total columns with more data: 45

In [29]:
# All columns where 2017 has less data
i = 0
for col in prop2017.columns:
    if prop2017[col].count() < prop2016[col].count():
        i+=1
        print('-----------------------------------------------')
        print('2017 %s count: %d' %(col, prop2017[col].count()))
        print('\n2016 %s count: %d' %(col, prop2016[col].count()))
        print('-----------------------------------------------\n')

print('Total columns with less data: %d' %i)

-----------------------------------------------
2017 basementsqft count: 1627

2016 basementsqft count: 1628
-----------------------------------------------

-----------------------------------------------
2017 finishedsquarefeet13 count: 7671

2016 finishedsquarefeet13 count: 7672
-----------------------------------------------

-----------------------------------------------
2017 finishedsquarefeet15 count: 190185

2016 finishedsquarefeet15 count: 190798
-----------------------------------------------

-----------------------------------------------
2017 finishedsquarefeet6 count: 21482

2016 finishedsquarefeet6 count: 22001
-----------------------------------------------

-----------------------------------------------
2017 hashottuborspa count: 50062

2016 hashottuborspa count: 69014
-----------------------------------------------

-----------------------------------------------
2017 poolsizesum count: 27958

2016 poolsizesum count: 27960
-----------------------------------------------

-----------------------------------------------
2017 pooltypeid10 count: 17006

2016 pooltypeid10 count: 36939
-----------------------------------------------

-----------------------------------------------
2017 storytypeid count: 1623

2016 storytypeid count: 1624
-----------------------------------------------

-----------------------------------------------
2017 typeconstructiontypeid count: 6746

2016 typeconstructiontypeid count: 6747
-----------------------------------------------

-----------------------------------------------
2017 yardbuildingsqft26 count: 2646

2016 yardbuildingsqft26 count: 2647
-----------------------------------------------

Total columns with less data: 10